# Generated by Django 3.0.4 on 2020-05-17 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agre', models.TextField()),
                ('reject', models.TextField()),
                ('bloodgroup', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bloodgroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agre', models.BooleanField(default=False, editable=False)),
                ('reject', models.BooleanField(default=False, editable=False)),
                ('memberdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('fname', models.CharField(max_length=25)),
                ('mname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('mobile1', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('mem_img', models.ImageField(upload_to='member_pics')),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agre', models.TextField()),
                ('reject', models.TextField()),
                ('relationtype', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'relationtype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemberPrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_name', models.CharField(max_length=100)),
                ('relativeid', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytree.Member')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytree.RelationType')),
            ],
            options={
                'db_table': 'memberprt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemberPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agre', models.TextField()),
                ('reject', models.TextField()),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('bloodgroup_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytree.Bloodgroup')),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytree.Member')),
            ],
            options={
                'db_table': 'memberpersonal',
                'managed': True,
            },
        ),
    ]
