# Generated by Django 3.0.4 on 2020-05-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberpersonal',
            old_name='bloodgroup_id',
            new_name='bloodgroup',
        ),
        migrations.RenameField(
            model_name='memberpersonal',
            old_name='member_id',
            new_name='member',
        ),
    ]
